name: "PR body contains license agreement"
on: [pull_request]

jobs:
  license_agreement:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v2
      with:
        github-token: ${{github.token}}
        bodyContains: 'By opening this pull request, I agree for my modifications to be licensed under whatever licenses are indicated at the start of the files I modified'
